### ISSUE TITLE
InterceptConnection flush no longer takes Channel argument

### ISSUE THREAD

**Issue by Kriechi** [Duet3D/dsf-python#11]
https://github.com/Duet3D/dsf-python/blob/8585a904a87f3782f09473cd179b06f72cf83ddc/src/dsf/connections.py#L460

now causes this example to be broken:
https://github.com/Duet3D/dsf-python/blob/8585a904a87f3782f09473cd179b06f72cf83ddc/examples/custom_m_codes.py#L34

**Comment by mfs12** [comment]
Commit 86c0764afe26367f091d4fa5e37b3cf332a151df introduces flush implementation in intercept_connections. This brings the problematic API change.

**Comment by Kriechi** [comment]
Yes, this seems to fix it.
What's the recommended way to flush now? With or without passing the channel?

**Comment by mfs12** [comment]
Default channel is now SBC, so if you are using alternatives then better use the codechannel parameter. To be honest i can't give you a clear recommendation for either.

**Comment by chrishamm** [comment]
@Kriechi @mfs12 I do. The reason the new Flush command has an optional channel arugment is because DSF keeps track of the current code channel where a code is intercepted. So if you implement a custom code, you don't need to worry about the source channel any more. If you - for whatever reason - need to flush from a command connection, the channel argument must not be omitted and defaults to the SBC channel.

**Comment by Kriechi** [comment]
@mfs12 does this also fix #7 ?
